### PR TITLE
/stripe/pay endpoint update

### PR DESCRIPTION
**Pull request by Mullefa**
cc
@guardian/contributions 
@guardian/ios-developers 
@guardian/android-developers 
@guardian/membership-and-subscriptions 

This pull request updates the`/stripe/pay` endpoint so that it no longer accepts content type`multipart/form-data`.

__Why?__ (1) we no longer make requests to this endpoint with content type`multipart/form-data` (confirmed by talking to the iOS and Android teams); removing it simplifies the code; and (2) it'll be simpler to de-bug parser errors (occurring in #341) as the parser is less complicated.

Have you gone through the contributions flow for all test variants ? __Yes, locally__

### CODE REVIEW

**Comment by maxspencer** [comment]
Hey, can you deploy this to the CODE environment (`https://contribute.code.dev-theguardian.com`) so I can test this change doesn't affect the Android app?

**Review by desbo — APPROVED** [review]
Looks good to me - agree that a CODE sanity check would be worthwhile.

**Comment by Mullefa** [comment]
@maxspencer this branch is now on CODE

**Comment by SLambrakis** [comment]
Tested on CODE on iOS. Looks good to me 👍

**Comment by Mullefa** [comment]
Nice one! Cheers 👍

**Comment by maxspencer** [comment]
I've just tested it on Android too and it worked fine 👍

**Review by maxspencer — APPROVED** [review]

**Comment by Mullefa** [comment]
Cheers - thanks for testing @SLambrakis and @maxspencer 👍

**Comment by Mullefa** [comment]
Good catch from @michaelwmcnamara - the endpoint is being used by S&C too, but they are also posting to the endpoint using JSON (cc @svillafe)

**Comment by svillafe** [comment]
Tested one off with Stripe from S&C and it is working. Thank you for letting me know @Mullefa

**Comment by Mullefa** [comment]
@svillafe 👍

**Pull request merged**
