### PR TITLE
Add recurring payments test

### PR DESCRIPTION
**Pull request by desbo**
A test for recurring payments!

sep 27 2016 17 20

In addition to the changes required for those visuals, this fires an Ophan `complete` event for the test so we can measure the results in Abacus, and also fires a GA event with a value so we can see the average amount people are choosing to pay each month. This doesn't include currency, so the results will be far from perfect, but should be indicative.

This ended up being much bigger than I expected, apologies for the massive PR :(

### CODE REVIEW

**Comment by AWare** [comment]
If you tab through the form and select monthly -> ok the focus drops off the end of the form.

**Comment by AWare** [comment]
The 25 is hoverable and the default selection changes on one-off. Also, might be worth letting the user just click on an amount and have it autoselect one-off? 

image
image

**Comment by desbo** [comment]
Thanks @AWare, I'll get to those now. Ben and Ali were pretty keen on the form being totally inactive until one of the options has been selected, and I agree, so I don't think we should make the amounts clickable until we've chosen one. Nick H is working on a bit of new copy for "How often?" that should make it clearer you have to click one of the options.

**Comment by AWare** [comment]
@desbo yeah, that makes sense.

**Comment by tomverran** [comment]
You could always link people who want to make recurring contributions to membership, at least for now!

**Comment by desbo** [comment]
cheers @tomverran, I've added that.

**Comment by desbo** [comment]
@AWare  squashed this mother down a bit! can I get a ✅ ?

**Review by AWare — APPROVED** [review]
🆗

**Pull request merged**
