### PR TITLE
Paypal endpoints updated

### PR DESCRIPTION
**Pull request by Mullefa**
cc @svillafe 
cc @guardian/android-developers (`/paypal/capture` endpoint updated)

See #359 for the motivation behind this pull request.

Have you gone through the contributions flow for all test variants ? __Yes, locally__

## Related PR: https://github.com/guardian/support-frontend/pull/275

### CODE REVIEW

**Comment by mohammad-haque** [comment]
@Mullefa I don't see any changes for `paypal/capture` in this PR. Is this deployed to code environment? I can check with android client in code before it goes to production.

**Comment by Mullefa** [comment]
@mohammad-haque I've updated the JSON expected by this endpoint (see `CaptureRequest.scala`). The branch is now deployed to CODE. Appreciate you running that check - thanks!

**Comment by mohammad-haque** [comment]
@Mullefa Looks like it is failing Paypal payment in code, Android client get 500 response code. Something isn't working!

**Comment by Mullefa** [comment]
Looks like it was Paypal Sandbox causing this error, as it is now working ok.

Me and @mohammad-haque intend to test one more time on Monday morning, then release.

**Comment by svillafe** [comment]
Tested with @Mullefa in CODE and is working. Related S&C's PR: https://github.com/guardian/support-frontend/pull/275

**Review by svillafe — APPROVED** [review]

**Pull request merged**
