### PR TITLE
Upgrade to cats 0.8.1

### PR DESCRIPTION
**Pull request by philwills**

### CODE REVIEW

**Review by alexduf — CHANGES_REQUESTED** [review]
Looks good, but it looks like TeamCity is grumpy

**Comment by philwills** [comment]
@alexduf I saw it lurking in my working directory, so pushed it, but apparently forgot that I hadn't actually got it to compile.

**Comment by philwills** [comment]
Now updated so that it actually compiles.

**Review by alexduf — APPROVED** [review]
👍

**Pull request merged**
