### PR TITLE
React more "secure" UX tweaks

### PR DESCRIPTION
**Pull request by alexduf**
screenshot from 2016-08-24 16-49-20

### CODE REVIEW

**Comment by alexduf** [comment]
cc @desbo

**Comment by desbo** [comment]
👍

**Comment by dbgdngit** [comment]
Folks,
A black padlock has no meaning in terms of trust and just putting the word secure doesn't add to that.
We should stick to international conventions when trying to represent trust or give a more meaningful phrase. What do we mean by secure?

**Comment by dbgdngit** [comment]
"Secure connection to our payments partner"

**Pull request merged**
