### PR TITLE
logging added when body parsers fail

### PR DESCRIPTION
**Pull request by Mullefa**
cc @guardian/contributions 

Logs parsing failures to facilitate investigating errors. 

_Have you gone through the contributions flow for all test variants ?_ __Yes__

### CODE REVIEW

**Comment by michaelwmcnamara** [comment]
One suggestion - I'd make the payment method that you are logging the error for more specific.
ie "Unable to parse body to a paypal auth request" , "Unable to parse a stripe contribution request"
This will make it easier to follow in the logs where numerous payments and processes often overlap.
Otherwise - looks good!

**Review by michaelwmcnamara — APPROVED** [review]
Perhaps make wording more descriptive as described above - otherwise looks good!

**Review by dominickendrick — APPROVED** [review]

**Comment by dominickendrick** [comment]
Can this be merged ?

**Comment by Mullefa** [comment]
yes, I'll look to merge this later today

**Pull request closed without merging**
