### PR TITLE
fix devSetup

### PR DESCRIPTION
**Pull request by alexduf**
remove `..` as it was here because of the project nesting

### CODE REVIEW

**Comment by AWare** [comment]
👍

**Comment by AWare** [comment]
@alexduf didn't we need to copy across git hooks too?

**Comment by alexduf** [comment]
@AWare woups, fixed

**Comment by alexduf** [comment]
closed in favour of https://github.com/guardian/contributions-frontend/compare/fix-dev-setup?expand=1

**Pull request closed without merging**
